# Domain: 1D boundary conditions and geometry helpers

abstract type AbstractBoundary1D end

"""
    OpenBoundary1D()

Boundary policy for unwrapped one-dimensional coordinates.
"""
struct OpenBoundary1D <: AbstractBoundary1D end

"""
    PeriodicBoundary1D(xmin, xmax; twist=0.0)
    PeriodicBoundary1D(L; twist=0.0)

Periodic one-dimensional boundary with optional twist phase. The `twist`
parameter may be either a scalar angle shared by every coordinate or a
coordinate-wise vector of angles.
"""
struct PeriodicBoundary1D{T} <: AbstractBoundary1D
    xmin::Float64
    xmax::Float64
    twist::T
end

_normalize_twist(twist::Real) = Float64(twist)

function _normalize_twist(twist::AbstractVector{<:Real})
    return Float64[Float64(theta) for theta in twist]
end

function PeriodicBoundary1D(xmin::Real, xmax::Real; twist::Union{Real,AbstractVector{<:Real}}=0.0)
    xlo = Float64(xmin)
    xhi = Float64(xmax)
    xhi > xlo || throw(ArgumentError("xmax must be greater than xmin"))
    twist_value = _normalize_twist(twist)
    return PeriodicBoundary1D{typeof(twist_value)}(xlo, xhi, twist_value)
end

PeriodicBoundary1D(L::Real; twist::Union{Real,AbstractVector{<:Real}}=0.0) =
    PeriodicBoundary1D(0.0, Float64(L); twist=twist)

"""
    isperiodic(bc) -> Bool

Return `true` for periodic boundaries and `false` for open boundaries.
"""
isperiodic(::OpenBoundary1D) = false
isperiodic(::PeriodicBoundary1D) = true

"""
    cell_length(bc) -> Real

Return the period for periodic boundaries. Open boundaries report `Inf`.
"""
cell_length(::OpenBoundary1D) = Inf
cell_length(bc::PeriodicBoundary1D) = bc.xmax - bc.xmin

"""
    cell_bounds(bc) -> Tuple

Return `(xmin, xmax)` for periodic boundaries. Open boundaries report
`(-Inf, Inf)`.
"""
cell_bounds(::OpenBoundary1D) = (-Inf, Inf)
cell_bounds(bc::PeriodicBoundary1D) = (bc.xmin, bc.xmax)

in_cell(::OpenBoundary1D, x::Real) = true
in_cell(bc::PeriodicBoundary1D, x::Real) = (bc.xmin <= x < bc.xmax)

"""
    wrap_coordinate(bc, x) -> Float64

Map `x` into the simulation cell for periodic boundaries. Open boundaries return `x`.
"""
wrap_coordinate(::OpenBoundary1D, x::Real) = Float64(x)

function _wrap_coordinate_with_winding(bc::PeriodicBoundary1D, x::Real)
    L = cell_length(bc)
    y = Float64(x) - bc.xmin
    winding = floor(Int, y / L)
    return y - L * winding + bc.xmin, winding
end

wrap_coordinate(bc::PeriodicBoundary1D, x::Real) = first(_wrap_coordinate_with_winding(bc, x))

"""
    wrap_position!(bc, R) -> R

Wrap all coordinates in `R` in-place for periodic boundaries.
"""
function wrap_position!(bc::AbstractBoundary1D, R::AbstractVector{T}) where {T<:Real}
    for i in eachindex(R)
        R[i] = convert(T, wrap_coordinate(bc, R[i]))
    end
    return R
end

"""
    wrap_position(bc, R) -> Vector{Float64}

Return a wrapped copy of `R`.
"""
function wrap_position(bc::AbstractBoundary1D, R::AbstractVector{<:Real})
    out = Vector{Float64}(undef, length(R))
    for i in eachindex(R)
        out[i] = wrap_coordinate(bc, R[i])
    end
    return out
end

"""
    wrap_position_with_phase(bc, R) -> (wrapped_R, phase_factor)

Return a wrapped copy of `R` and the complex phase factor generated by any
periodic-cell crossings. For open or untwisted periodic boundaries, the phase
factor is `1 + 0im`.
"""
function wrap_position_with_phase(bc::AbstractBoundary1D, R::AbstractVector{<:Real})
    return wrap_position(bc, R), 1.0 + 0.0im
end

function _twist_phase_factor(bc::PeriodicBoundary1D, windings::AbstractVector{<:Integer})
    twist = bc.twist
    if twist isa Real
        total_winding = 0
        @inbounds for winding in windings
            total_winding += winding
        end
        return cis(Float64(twist) * total_winding)
    end

    length(twist) == length(windings) ||
        throw(ArgumentError("Twist vector length $(length(twist)) does not match coordinate dimension $(length(windings))"))

    phase_angle = 0.0
    @inbounds for i in eachindex(windings)
        phase_angle += Float64(twist[i]) * windings[i]
    end
    return cis(phase_angle)
end

function wrap_position_with_phase(bc::PeriodicBoundary1D, R::AbstractVector{<:Real})
    out = Vector{Float64}(undef, length(R))
    windings = Vector{Int}(undef, length(R))
    @inbounds for i in eachindex(R)
        out[i], windings[i] = _wrap_coordinate_with_winding(bc, R[i])
    end
    return out, _twist_phase_factor(bc, windings)
end

"""
    minimum_image(bc, dx) -> Float64

Return displacement under minimum-image convention.
"""
minimum_image(::OpenBoundary1D, dx::Real) = Float64(dx)

function minimum_image(bc::PeriodicBoundary1D, dx::Real)
    L = cell_length(bc)
    d = Float64(dx)
    return d - L * floor((d + 0.5 * L) / L)  # maps to [-L/2, L/2)
end

function minimum_image(bc::AbstractBoundary1D, dR::AbstractVector{<:Real})
    out = Vector{Float64}(undef, length(dR))
    for i in eachindex(dR)
        out[i] = minimum_image(bc, dR[i])
    end
    return out
end

"""
    displacement(bc, x_from, x_to) -> Float64

Shortest signed displacement from `x_from` to `x_to`.
"""
displacement(bc::AbstractBoundary1D, x_from::Real, x_to::Real) = minimum_image(bc, x_to - x_from)

function displacement(bc::AbstractBoundary1D, R_from::AbstractVector{<:Real}, R_to::AbstractVector{<:Real})
    length(R_from) == length(R_to) || throw(ArgumentError("R_from and R_to must have equal length"))
    out = Vector{Float64}(undef, length(R_from))
    for i in eachindex(R_from, R_to)
        out[i] = displacement(bc, R_from[i], R_to[i])
    end
    return out
end

"""
    distance_1d(bc, x1, x2) -> Float64

Minimum-image distance between two scalar coordinates.
"""
distance_1d(bc::AbstractBoundary1D, x1::Real, x2::Real) = abs(displacement(bc, x1, x2))

"""
    squared_distance_1d(bc, x1, x2) -> Float64

Squared minimum-image distance between two scalar coordinates.
"""
squared_distance_1d(bc::AbstractBoundary1D, x1::Real, x2::Real) = abs2(displacement(bc, x1, x2))
